export const genericWords = new Set([
  "the", "and", "a", "to", "of", "in", "i", "is", "that", "it", "on", "you",
  "this", "for", "but", "with", "are", "have", "be", "at", "or", "as", "was",
  "so", "if", "out", "not", "we", "us", "your", "my", "their", "who", "what",
  "when", "where", "how", "why", "which", "about", "into", "through", "during",
  "before", "after", "above", "below", "from", "up", "down", "off", "over",
  "under", "again", "further", "then", "once", "here", "there",
  "job", "role", "team", "company", "looking", "join", "our", "work", "skilled",
  "position", "opportunity", "career", "growth", "environment",
  "india", "bangalore", "location", "employment", "type", "full", "time",
  "part", "dynamic",
  "years", "year", "months", "month", "experience",
  "pvt", "ltd", "limited", "corporation", "corp", "inc", "incorporated",
  "technologies", "technology", "solutions", "services", "systems",
  "group", "industries", "enterprises", "llc", "plc", "gmbh", "llp",
  "pune", "mumbai", "delhi", "maharashtra", "city", "state", "country",
  "address", "remote", "hybrid",
  "description", "responsibilities", "qualification", "compensation",
  "salary", "benefits", "package", "lpa",
  "contact", "apply", "interested", "candidates", "send", "updated",
  "subject", "line", "name", "email", "phone", "website",
  "develop", "maintain", "design", "implement", "write", "create", "build",
  "manage", "lead", "oversee", "coordinate", "collaborate", "communicate",
  "analyze", "evaluate", "identify", "resolve", "troubleshoot",
  "provide", "support", "ensure", "perform", "prepare", "review", "test",
  "deploy", "monitor", "optimize", "improve", "enhance", "integrate",
  "configure", "install", "upgrade", "migrate", "document", "report",
  "participate",
  "including", "various", "multiple", "several", "certain", "specific",
  "particular", "individual", "additional", "relevant", "required",
  "preferred", "desired", "essential", "minimum", "ideal",
  "excellent", "good", "solid", "proven", "demonstrated", "effective",
  "efficient", "appropriate", "timely", "regular", "ongoing", "continuous",
  "related", "following", "based", "using", "such", "like", "well", "also",
  "just", "much", "many", "some", "any", "all", "both", "each", "every",
  "other", "another", "more", "most", "least", "less", "few",
  "than", "then", "else", "even", "still", "already", "always", "never",
  "often", "sometimes", "usually", "typically", "commonly", "frequently",
  "within", "without", "between", "among", "whether", "either", "neither",
  "able", "ability", "skill", "skills", "knowledge",
  "abc", "xyz", "test", "sample", "example", "demo", "dummy",
  "bachelor", "degree", "science", "engineering", "mathematics",
  "university", "college", "school", "education", "qualification",
  "graduate", "postgraduate", "master", "phd",
  "must", "need", "should", "could", "would", "shall", "may", "might",
  "can", "will", "plus",
]);
